n1=input("Enter the first number: ")
n2=input("Enter the second number: ")
n1=int(n1)
n2=int(n2)
Addition=(n1+n2)
Substraction=(n1-n2)
Multiplication=(n1*n2)
Division=(n1/n2)
print()
print()
print("Addition: ",Addition)
print("Substraction: ",Substraction)
print("Multiplication: ",Multiplication)
print("Division: ",Division)